// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using scenefile;
//
//    var sceneFile = SceneFile.FromJson(jsonString);

namespace scenefile
{
    using System;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SceneFileResponse
    {
        [JsonProperty("uploadSASUrl")]
        public String UploadSasUrl { get; set; }

        [JsonProperty("id")]
        public String Id { get; set; }

        [JsonProperty("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("lastModifiedAt")]
        public DateTimeOffset LastModifiedAt { get; set; }

        [JsonProperty("blobUrl")]
        public String BlobUrl { get; set; }

        [JsonProperty("sceneId")]
        public String SceneId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("contentType")]
        public string ContentType { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class SceneFileResponse
    {
        public static SceneFileResponse FromJson(string json) => JsonConvert.DeserializeObject<SceneFileResponse>(json, scenefile.ConverterSceneFileResponse.Settings);
    }

    public static class SerializeSceneFileResponse
    {
        public static string ToJson(this SceneFileResponse self) => JsonConvert.SerializeObject(self, scenefile.ConverterSceneFileResponse.Settings);
    }

    internal static class ConverterSceneFileResponse
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
